### ISSUE TITLE
Combining :ExrcEdit and :ExrcTrust

### ISSUE THREAD

**Issue by samhh** [ii14/exrc.vim#1]
Thanks for the plugin!

It's quite common that I `:ExrcEdit` (or `:e .exrc`) and then `:ExrcTrust`. I suspect this pattern is common enough to justify a new option, something like `:ExrcInit`, which would implicitly (if file's not already present for security concerns):

1. `:ExrcEdit`
2. `:w`
3. `:ExrcTrust`

Thus I can just hit a single command and be on my way without having to remember to trust the file I just saw myself create. :slightly_smiling_face:

**Comment by ii14** [comment]
Not sure if I understood your question correctly. You'd like to have a command that creates an empty `.exrc` file and then trusts it? If so then I don't see any benefit because: 1. you're trusting an empty file, 2. when the contents of the file change that file is no longer trusted, so if you want to edit your trusted `.exrc`, you have to still do `:ExrcTrust`.

Instead you can automatically call `:ExrcTrust` on save. This will also work for freshly created files, like `:e .exrc | w`.
```vim
autocmd BufWritePost .exrc nested ExrcTrust
```

`:ExrcTrust` defaults to the current file, but you can specify what file you want to trust, eg. `:ExrcTrust path/to/.exrc`.

Good thing you're bringing this up though, because I forgot to allow combining `:Exrc*` commands with `|`. I'll fix it and then you will be able to do `:ExrcEdit | w | ExrcTrust` in one go if you really want to.

**Comment by ii14** [comment]
If you don't want to automatically trust files on save, because you type faster than you think and you don't even trust yourself (not judging anyone, I get it), you might prefer something like this:
```vim
autocmd BufNewFile .exrc nested autocmd BufWritePost <buffer> nested ExrcTrust
```
This will automatically trust file on save only for `.exrc` files you've just created.

**Comment by samhh** [comment]
That's perfect for my use case, thank you!
